default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  <<: *default
  database: rails_ecomm_dev
  host: localhost

test:
  <<: *default
  database: rails_ecomm_test
  host: localhost

production:
  <<: *default
